//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdtuTube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int tag_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> like { get; set; }
        public Nullable<int> view { get; set; }
        public bool privacy { get; set; }
        public string length { get; set; }
        public string thumbnail { get; set; }
        public string path { get; set; }
        public bool feature { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual User User { get; set; }
    }
}
